config/routes.rb
Hitchens::Application.routes.draw do

  resources :virus_characteristics

  resources :characteristics

  resources :viruses

  resources :user_locations do
      collection do
          delete 'delete_all'
      end
  end
  
  resources :users
  
  resource :virus_characteristics
  
  root :to => "users#index"

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  has_many :virus_characteristics
  has_many :viruses, :through => :virus_characteristics


  attr_accessible :characteristic, :description
  validates :characteristic, :description, :presence => true

end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  # GET /characteristics
  # GET /characteristics.json
  def index
    @characteristics = Characteristic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characteristics }
    end
  end

  # GET /characteristics/1
  # GET /characteristics/1.json
  def show
    @characteristic = Characteristic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @characteristic }
    end
  end

  # GET /characteristics/new
  # GET /characteristics/new.json
  def new
    @characteristic = Characteristic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @characteristic }
    end
  end

  # GET /characteristics/1/edit
  def edit
    @characteristic = Characteristic.find(params[:id])
  end

  # POST /characteristics
  # POST /characteristics.json
  def create
    @characteristic = Characteristic.new(params[:characteristic])

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully created.' }
        format.json { render json: @characteristic, status: :created, location: @characteristic }
      else
        format.html { render action: "new" }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characteristics/1
  # PUT /characteristics/1.json
  def update
    @characteristic = Characteristic.find(params[:id])

    respond_to do |format|
      if @characteristic.update_attributes(params[:characteristic])
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.json
  def destroy
    @characteristic = Characteristic.find(params[:id])
    @characteristic.destroy

    respond_to do |format|
      format.html { redirect_to characteristics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_form.html.erb
<%= form_for(@characteristic) do |f| %>
  <% if @characteristic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@characteristic.errors.count, "error") %> prohibited this characteristic from being saved:</h2>

      <ul>
      <% @characteristic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :characteristic %><br />
    <%= f.text_field :characteristic %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characteristics/edit.html.erb
<h1>Editing characteristic</h1>

<%= render 'form' %>

<%= link_to 'Show', @characteristic %> |
<%= link_to 'Back', characteristics_path %>

app/views/characteristics/index.html.erb
<h1>Virus Characteristics</h1>

<table>
  <tr>
    <th>Characteristic</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characteristics.each do |characteristic| %>
  <tr>
    <td><%= characteristic.characteristic %></td>
    <td class="left"><%= characteristic.description %></td>
    <td><%= link_to_icon 'Show', characteristic %></td>
    <td><%= link_to_icon 'Edit', edit_characteristic_path(characteristic) %></td>
    <td><%= link_to_icon 'Destroy', characteristic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to "New Virus Characteristic", new_characteristic_path%>

app/views/characteristics/new.html.erb
<h1>New characteristic</h1>

<%= render 'form' %>

<%= link_to 'Back', characteristics_path %>

app/views/characteristics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Characteristic:</b>
  <%= @characteristic.characteristic %>
</p>

<p>
  <b>Description:</b>
  <%= @characteristic.description %>
</p>


<%= link_to 'Edit', edit_characteristic_path(@characteristic) %> |
<%= link_to 'Back', characteristics_path %>