config/routes.rb
Hitchens::Application.routes.draw do

  resources :virus_characteristics

  resources :characteristics

  resources :viruses

  resources :user_locations do
      collection do
          delete 'delete_all'
      end
  end
  
  resources :users
  
  resource :virus_characteristics
  
  root :to => "users#index"

end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :latlon, :send_method, :timestamp   
  
  validates :user_id, :latlon, :send_method, :timestamp, :presence => true 
  
  EWKB = RGeo::WKRep::WKBGenerator.new(:type_format => :ewkb, :emit_ewkb_srid => true, :hex_format => true)
      
  # Create a simple mercator factory. This factory itself is
  # geographic (latitude-longitude) but it also contains a
  # companion projection factory that uses EPSG 3785.
  FACTORY = RGeo::Geographic.simple_mercator_factory

  # We're storing data in the database in the projection.
  # So data pulled straight from the "latlon" attribute will be in
  # projected coordinates.
  set_rgeo_factory_for_column(:latlon, FACTORY.projection_factory)

  # To interact in projected coordinates, just use the "latlon"
  # attribute directly.
  def latlon_projected
    self.latlon
  end
  def latlon_projected=(value)
    self.latlon = value
  end

  # To use geographic (lat/lon) coordinates, convert them using
  # the wrapper factory.
  def latlon_geographic
    FACTORY.unproject(self.latlon)
  end
  def latlon_geographic=(value)
    self.latlon = FACTORY.project(value)
  end
  
  def self.get_intersections
      segment = EWKB.generate(FACTORY.project(line_string))
      
  end
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
  # GET /user_locations
  # GET /user_locations.json
  def index
    @user_locations = UserLocation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_locations }
    end
  end

  # GET /user_locations/1
  # GET /user_locations/1.json
  def show
    @user_location = UserLocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_location }
    end
  end

  # GET /user_locations/new
  # GET /user_locations/new.json
  def new
    @user_location = UserLocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_location }
    end
  end

  # GET /user_locations/1/edit
  def edit
    @user_location = UserLocation.find(params[:id])
  end

  # POST /user_locations
  # POST /user_locations.json   curl -H "Content-Type:application/json" -H "Accept:application/json" -X POST -d '{"user_location":{"user_id":1,"latlon":"SRID=3785;POINT(-124.123456 44.123456)", "send_method":"curl","timestamp":"2012-06-06 11:55:00 +000"}}' http://localhost:5000/user_locations
  def create
    @user_location = UserLocation.new(params[:user_location])

    respond_to do |format|
      if @user_location.save
        format.html { redirect_to @user_location, notice: 'User location was successfully created.' }
        format.json { render json: @user_location, status: :created, location: @user_location }
      else
        format.html { render action: "new" }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_locations/1
  # PUT /user_locations/1.json
  def update
    @user_location = UserLocation.find(params[:id])

    respond_to do |format|
      if @user_location.update_attributes(params[:user_location])
        format.html { redirect_to @user_location, notice: 'User location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_locations/1
  # DELETE /user_locations/1.json
  def destroy
    @user_location = UserLocation.find(params[:id])
    @user_location.destroy

    respond_to do |format|
      format.html { redirect_to user_locations_url }
      format.json { head :no_content }
    end
  end
  
  # DELETE all
  def delete_all
    UserLocation.delete_all
    
    respond_to do |format|
      format.html { redirect_to user_locations_url }
      format.json { head :no_content }
    end
  end
     
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
    
    def user_locations_links(user_location)
            content_tag :tr do
                [   content_tag(:td, user_location.user_id), 
                    content_tag(:td, user_location.latlon), 
                    content_tag(:td, user_location.send_method), 
                    content_tag(:td, user_location.timestamp),
                    content_tag(:td, link_to_icon('show', user_location)), 
                    content_tag(:td, link_to_icon('edit', edit_user_location_path(user_location))),
                    content_tag(:td, link_to_icon('destroy', user_location, {
                                :confirm => 'Are you sure?',
                                :method => :delete
                                })
                            )
                    ].join(' ').html_safe
        end
    end
end

app/views/user_locations/_form.html.erb
<%= form_for(@user_location) do |f| %>
  <% if @user_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_location.errors.count, "error") %> prohibited this user_location from being saved:</h2>

      <ul>
      <% @user_location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :Point %><br />
    <%= f.text_field :latlon %>
  </div>
  <div class="field">
    <%= f.label :send_method %><br />
    <%= f.text_field :send_method %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.time_select :timestamp %>
  </div>
  <div class="test">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_locations/_user_location.html.erb
<%= user_locations_links(user_location) %>

app/views/user_locations/edit.html.erb
<h1>Editing User Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_location %> |
<%= link_to 'Back', user_locations_path %>

app/views/user_locations/index.html.erb
<h1>User Locations</h1>
<div> <%= link_to t('delete_all'), delete_all_user_locations_path, confirm: 'Delete all user locations?', :method => :delete %></div>
<br />
<table>
		<tr class=header>
			<td>
				User id
			</td>
			<td>
				Point
			</td>
			<td>
				Send Method
			</td>
			<td>
				Time Stamp
			</td>
		</tr>
<%= render @user_locations %>
</table>
<br />
<%= link_to "New User Location", new_user_location_path%>

app/views/user_locations/new.html.erb
<h1>New User Location</h1>

<%= render 'form' %>

<%= link_to 'Back', user_locations_path %>

app/views/user_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_location.user_id %>
</p>

<p>
  <b>Location:</b>
  <%= @user_location.latlon %>
</p>
     
<p>
  <b>Send Method:</b>
  <%= @user_location.send_method %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @user_location.timestamp %>
</p>


<%= link_to 'Edit', edit_user_location_path(@user_location) %> |
<%= link_to 'Back', user_locations_path %>