config/routes.rb
Hitchens::Application.routes.draw do

  resources :virus_characteristics

  resources :characteristics

  resources :viruses

  resources :user_locations do
      collection do
          delete 'delete_all'
      end
  end
  
  resources :users
  
  resource :virus_characteristics
  
  root :to => "users#index"

end

app/models/virus_characteristic.rb
class VirusCharacteristic < ActiveRecord::Base
  attr_accessible :characteristic_id, :characteristic_level, :virus_id
end

app/controllers/virus_characteristics_controller.rb
class VirusCharacteristicsController < ApplicationController
  # GET /virus_characteristics
  # GET /virus_characteristics.json
  def index
    @virus_characteristics = VirusCharacteristic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @virus_characteristics }
    end
  end

  # GET /virus_characteristics/1
  # GET /virus_characteristics/1.json
  def show
    @virus_characteristic = VirusCharacteristic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @virus_characteristic }
    end
  end

  # GET /virus_characteristics/new
  # GET /virus_characteristics/new.json
  def new
    @virus_characteristic = VirusCharacteristic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @virus_characteristic }
    end
  end

  # GET /virus_characteristics/1/edit
  def edit
    @virus_characteristic = VirusCharacteristic.find(params[:id])
  end

  # POST /virus_characteristics
  # POST /virus_characteristics.json
  def create
    @virus_characteristic = VirusCharacteristic.new(params[:virus_characteristic])

    respond_to do |format|
      if @virus_characteristic.save
        format.html { redirect_to @virus_characteristic, notice: 'Virus characteristic was successfully created.' }
        format.json { render json: @virus_characteristic, status: :created, location: @virus_characteristic }
      else
        format.html { render action: "new" }
        format.json { render json: @virus_characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /virus_characteristics/1
  # PUT /virus_characteristics/1.json
  def update
    @virus_characteristic = VirusCharacteristic.find(params[:id])

    respond_to do |format|
      if @virus_characteristic.update_attributes(params[:virus_characteristic])
        format.html { redirect_to @virus_characteristic, notice: 'Virus characteristic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @virus_characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /virus_characteristics/1
  # DELETE /virus_characteristics/1.json
  def destroy
    @virus_characteristic = VirusCharacteristic.find(params[:id])
    @virus_characteristic.destroy

    respond_to do |format|
      format.html { redirect_to virus_characteristics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/virus_characteristics_helper.rb
module VirusCharacteristicsHelper
end

app/views/virus_characteristics/_form.html.erb
<%= form_for(@virus_characteristic) do |f| %>
  <% if @virus_characteristic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@virus_characteristic.errors.count, "error") %> prohibited this virus_characteristic from being saved:</h2>

      <ul>
      <% @virus_characteristic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :virus_id %><br />
    <%= f.number_field :virus_id %>
  </div>
  <div class="field">
    <%= f.label :characteristic_id %><br />
    <%= f.number_field :characteristic_id %>
  </div>
  <div class="field">
    <%= f.label :characteristic_level %><br />
    <%= f.number_field :characteristic_level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/virus_characteristics/edit.html.erb
<h1>Editing virus_characteristic</h1>

<%= render 'form' %>

<%= link_to 'Show', @virus_characteristic %> |
<%= link_to 'Back', virus_characteristics_path %>

app/views/virus_characteristics/index.html.erb
<h1>Listing virus_characteristics</h1>

<table>
  <tr>
    <th>Virus</th>
    <th>Characteristic</th>
    <th>Characteristic level</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @virus_characteristics.each do |virus_characteristic| %>
  <tr>
    <td><%= virus_characteristic.virus_id %></td>
    <td><%= virus_characteristic.characteristic_id %></td>
    <td><%= virus_characteristic.characteristic_level %></td>
    <td><%= link_to_icon 'Show', virus_characteristic %></td>
    <td><%= link_to_icon 'Edit', edit_virus_characteristic_path(virus_characteristic) %></td>
    <td><%= link_to_icon 'Destroy', virus_characteristic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Virus characteristic', new_virus_characteristic_path %>

app/views/virus_characteristics/new.html.erb
<h1>New virus_characteristic</h1>

<%= render 'form' %>

<%= link_to 'Back', virus_characteristics_path %>

app/views/virus_characteristics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Virus:</b>
  <%= @virus_characteristic.virus_id %>
</p>

<p>
  <b>Characteristic:</b>
  <%= @virus_characteristic.characteristic_id %>
</p>

<p>
  <b>Characteristic level:</b>
  <%= @virus_characteristic.characteristic_level %>
</p>


<%= link_to 'Edit', edit_virus_characteristic_path(@virus_characteristic) %> |
<%= link_to 'Back', virus_characteristics_path %>